### ISSUE TITLE
Spelling Errors

### ISSUE THREAD

**Issue by joshbaldwin** [bySabi/karma-istanbuljs-reporter#2]
The examples given in the readme and the variables in the code do not match up on two elements.  I believe the code should be changed to match the examples since the examples look more consistent and how one might expect the variables to look.

In the example we have:
{
  lines: 90,
  **functions**: 0,
  **statements**: 0,
  branches: 0
}

In index.js we currently have:
var thresholds = checkCoverage ? {
    lines: checkCoverage.lines || 90,
    functions: checkCoverage.**function** || 0,
    statements: checkCoverage.**statments** || 0,
    branches: checkCoverage.branches || 0
}

index.js **should** look like this:
 var thresholds = checkCoverage ? {
    lines: checkCoverage.lines || 90,
    functions: checkCoverage.**functions** || 0,
    statements: checkCoverage.**statements** || 0,
    branches: checkCoverage.branches || 0
}

That is, "statments" should be "statements" and "function" should be "functions".

Please let me know if you would like me to make these code changes.  They are so minor I'm not sure if it is easier for you to make.

**Comment by bySabi** [comment]
@joshbaldwin please make a PR for this.

Thanks for report it 👍

**Comment by bySabi** [comment]
Published update package: `0.2.0` and I added you like a contributor.

Regards!

**Comment by joshbaldwin** [comment]
Yes sir!  Thank you!
